name: aioCloud CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          bash build.sh
          ls -al releases || true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: releases
          path: |
            releases/SHA256SUMS.txt
            releases/stream-*.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: true
          files: |
            releases/SHA256SUMS.txt
            releases/stream-*.zip
          body: |
            ## 更新日志
            * 将会很快更新
